{% set name = "refnx" %}
{% set version = "0.1.4" %}
{% set sha256 = "57d36fc38a1d1c46a849c3033a71d13da6e480b7b2535b095756cde5ec55dd07" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/refnx/refnx/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

  skip: true  # [py27]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - cython
    - setuptools

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - xlrd
    - pandas
    - h5py
    - matplotlib
    - ipywidgets
    - traitlets
    - corner
    - tqdm

test:
  requires:
    - pytest
    - nose
    - uncertainties
    - scipy>=1.2.0
  commands:
    - py.test --pyargs refnx -v --duration=0

  imports:
    - refnx

about:
  home: https://github.com/refnx/refnx
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Neutron and X-ray Reflectometry Analysis'
  doc_url: https://refnx.github.io

extra:
  recipe-maintainers:
    - andyfaff
