travis:
  secure:
    BINSTAR_TOKEN: vrUFOKNGDwIEkWUOToTgibG5o11rsIHyCuP/WEnUHjBX9K7sioRq6o/osCFh3mdkornXQFnnPELeRVq42CfhGODVCgeamF0Fvk+zqD8q8wSbtCmoNGnwD1YlgFx/KZV6PAVLJOnL6eemZOE6OTl10bgy5aebIyZlW1V2l6Ali30GIWC+vMIKKo1ZIqpiBQKePN3twCONVHKY73MQhxfPWkiEb07NmmGGmG6Pomu5qwwSP8MRmYPnNPt+dR3XVmrsJGiJCCEUN8BBXFytaZVkWAkHCx9FfKcv+RhBn+CK/UolL3fokeeElucSk0+3a5qgENlSAW8/labxOR4/LnJ8bK8AOILHbWIApCTnnRalaUD5fPQPH+ZgPwzvOR2qlgQybaT1U9gm09aG6f9CjLuK4M3B5kysRlVsCbf9Lt68/Bb0NcaR/tGTulgz1MpJgklqbw4EML4j4qcvrRvv3zM+KI/nkT61q3SywETWd1h0YSm355zed2tm6pFpmuWxutjA+DMNcNw+9dzmAxNfJng99zYV6yKdqUFmSVorCvoyyXz/XjkkQfE5cD8XLQXlO9sZisWGrc3Py6116gIjEAUZmKsomibSC6cawpXVZxurDp8lk4eGjvnfIXs6ZUXFWmOoGvXsiUkAyInYotu6zr63bR5SHx3NFocC98Ap/GG5vtk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
